global:
    evaluation_interval: 30s
    external_labels: null
    scrape_interval: 15s
    scrape_timeout: 10s

rule_files:
- /etc/prometheus/rules/*.rules.yml

scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://10.200.22.167:7001
        - redis://10.200.22.167:7002
        - redis://10.200.22.167:7003
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.200.22.167:9121
  
  -  job_name: 'node'
     scrape_interval: 8s
     static_configs:
       -  targets:
          - 10.200.22.241:9100
alerting:
    alertmanagers:
    -   static_configs:
        -   targets:
            - localhost:9093
